### PR TITLE
added loop to createLayer options

### PR DESCRIPTION
**Pull request by csobier**
For [Docs Issue#717](https://github.com/CartoDB/docs/issues/717).  @michellechandra , please review and advise.
- I added this an an option to createLayer and linked to the Torque.js doc. (Loop is already documented in the Torque API methods). 
- This is only applicable to createLayer, not createVis, right?
- Does this also need to be included in the [MapConfig, Torque Layer Options](http://docs.cartodb.com/cartodb-platform/maps-api/mapconfig/#torque-layer-options)?

### CODE REVIEW

**Comment by michellechandra** [comment]
@csobier - looks good, here is an issue I opened re: loop not part of createVis: https://github.com/CartoDB/cartodb.js/issues/1172

**Comment by csobier** [comment]
@alonsogarciapablo , can I add this update to the docs if this looks OK to you?  (Also, please advise if this should also be added to the Map Configs- Torque layer doc?)

**Comment by alonsogarciapablo** [comment]
:+1: If that's how it works. I realized you're using \`\`\`true\`\`\` and \`\`\`false\`\`\`, but \`true\` would work too (simpler)

**Comment by csobier** [comment]
Thanks!  I will merge once I figure out what is happening with the code (I didn't write it like that, something is happening programmatically with the code in the docs. I've asked @matallo to look into this).

**Comment by xavijam** [comment]
retest this please

**Comment by csobier** [comment]
Thanks for the fix @xavijam !

**Pull request merged**
