### PR TITLE
Fixes some typos and introduces some changes to API.md

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
I was reading the docs to learn about cartodb.js...
I found a typo..
I cloned the repo to fix THE typo...

...I ended up fixing more typos and changing a bunch of things.

:expressionless:

### CODE REVIEW

**Comment by javisantana** [comment]
@ohasselblad could you check this PR and merge ?

**Comment by ohasselblad** [comment]
sure, no problem

**Comment by ohasselblad** [comment]
@javisantana there are a couple of things I want to edit but I don't have push access to this PR

**Comment by ohasselblad** [comment]
@javisantana nevermind, figured it out :+1:

**Comment by ohasselblad** [comment]
@alonsogarciapablo +1000 for all the edits!!

**Comment by alonsogarciapablo** [comment]
@ohasselblad You're welcome!

**Pull request merged**
