### PR TITLE
Change linter to semistandard

### PR DESCRIPTION
**Pull request by viddo**
Same as [standard but with semicolons](https://github.com/Flet/semistandard#rules), as requested offline and https://github.com/CartoDB/cartodb.js/pull/928#issuecomment-165036919

@javisantana @alonsogarciapablo OK with you? This PR was a 5-min change so no biggie. 
cc @CartoDB/frontend FYI

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
:+1:, but didn't you guys agree to remove the semicolons? why are we bringing them back?

**Comment by alonsogarciapablo** [comment]
Should we remove the `.eslintignore` if we bring the semicolons back (and we shouldn't have so many warnings)?

**Comment by viddo** [comment]
We agreed to apply standardjs which included removing the semicolons, but judging from responses afterwards I get the perception that not everyone actually agreed in the end (did not read its rules perhaps?). Also, I interpret @javisantana's https://github.com/CartoDB/cartodb.js/pull/928#issuecomment-165036919 as this is a no-go (correct me if I'm wrong).

As this PR shows, luckily it's not a big deal to fix that particular request.

**Comment by viddo** [comment]
Removing `.eslintignore` and applying using autoformat…
```bash
grunt standard:lint | wc -l
    1930
```
…there's still a significant amount of offending rules that need manual fixing. I would not bother with these for now.

**Comment by javisantana** [comment]
My comment is to expose I was not agree but it's not a blocker just an opinion (an opinion + 2 reasons about why keeping semicolons is important)

**Comment by viddo** [comment]
Okie doki, then I close this PR :kissing_heart:

**Comment by javisantana** [comment]
hey, it was an opinion that you should not ignore. I think I'm right

**Comment by viddo** [comment]
Ok, then I misunderstood your comment as "disagree and commit". 
I do not have a strong opinion on the semicolons. So if you want the semicolons let's merge this then?

**Comment by javisantana** [comment]
I take that as a disagree and commit from your side

**Pull request merged**
