### PR TITLE
Improves xAxis calculation

### PR DESCRIPTION
**Pull request by javierarce**
Now the elements of the axis are linked to the vertical lines: 

Example with 4 divisions:
screen shot 2015-11-17 at 17 43 39

Example with 6 divisions:
screen shot 2015-11-17 at 17 44 02

### CODE REVIEW

**Comment by javierarce** [comment]
@viddo, @saleiva: can you have a look, please?

**Comment by javierarce** [comment]
BTW: I just realised that right now we are using 4 fixed divisions but the number should be dynamic depending on the width of the histogram… I'm adding a fix to calculate the # of divisions dynamically.

**Comment by saleiva** [comment]
Ossom,

LMK when done so we takr a look :)

**Comment by viddo** [comment]
Looks legit :+1:

**Pull request merged**
