### PR TITLE
🔥 Clean up `cdb` object and remove unused stuff 🔥

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
There's an internal `cdb` object which is "exported" to window as `window.carto` and `window.cdb` ([here](https://github.com/CartoDB/cartodb.js/blob/cdb-cleanup/src/cartodb.js#L9)). This object used to be a mechanism to namespace things, but it's no longer necessary. We'll have to figure out something similar when we start working on the new API.

Also, this PR removes `Map#isBaseLayerAdded` and `LayerModelBase#isEqual` and `Loader.loadModule`, which are no longer used.

cc: @rochoa

### CODE REVIEW

**Comment by donflopez** [comment]
Also, I'd wait to have our main task merged to avoid side effects

**Comment by alonsogarciapablo** [comment]
cc: @xavijam it'd be great if you could confirm / double-check that only the following "namespaced" classes / functions are used in BUILDER:

cdb.core.sanitize
cdb.core.Template
cdb.core.Model
cdb.core.View
cdb.SQL
cdb.createVis

 Thanks!

**Comment by xavijam** [comment]
Checked code in Builder and these are the functions we use:

- cdb.Core.View
- cdb.core.Template
- cdb.core.sanitize
- cdb.core.Model

**Comment by alonsogarciapablo** [comment]
Merging into `remove-old-code` branch.

**Comment by alonsogarciapablo** [comment]
Thanks @xavijam!

**Pull request merged**
