### PR TITLE
Require torque with github repository instead of version

### PR DESCRIPTION
**Pull request by xavijam**
@rochoa @javisantana

### CODE REVIEW

**Comment by xavijam** [comment]
The problem using versioning here is, if we change something in torque.js, and we don't bump the package version, running `npm install` will not update anything from that dependency because it thinks it is the same.

**Comment by rochoa** [comment]
IMO we should not use a branch for a dependency.

BTW why did you have to change those tests?/

**Comment by xavijam** [comment]
Related with last changes in torque, testing that `Map {}` is present in the `cartocss`.
https://github.com/CartoDB/torque/commit/0e9184e02629c07a6323c8fc955e2760f6710226

**Comment by xavijam** [comment]
If we don't use a branch, we should take care of the version, I'm ok with that, but if it has happened once, it could happen again.

**Comment by rochoa** [comment]
I'm lost: what was the problem?

**Comment by xavijam** [comment]
We have to publish the version to NPM.

**Pull request closed without merging**
