### PR TITLE
adding google heatmap tutorial code

### PR DESCRIPTION
**Pull request by michellechandra**

### CODE REVIEW

**Comment by michellechandra** [comment]
@andrewxhill @javisantana 

Adding Google Heatmap tutorial code.

tutorial-google-heatmap.html - example code people will refer to for the tutorial
tutorial-google-heatmap-2.html - map code to be hosted on gh pages so can be included at the top of the tutorial page, uses a Google for Work account

**Comment by javisantana** [comment]
the code looks good. Do we want to have examples of google heatmaps instead of using our heatmaps?

**Comment by andrewxhill** [comment]
So, this ticket predated our own heatmaps. It cannot hurt though, but I think we should add a paragraph to the top saying that you can also do heatmaps with cartocss and that they will scale a lot better. 

let me take a look

**Comment by javisantana** [comment]
it's ok.

FYI: using geojson format is less optimal than user json with "select st_x(the_geom) as lon, st_y(the_geom) as lat from table". For this case I'd not change it since geojson is a well known format

**Pull request merged**
