### PR TITLE
Change viz api calls to https in examples

### LINKED ISSUE #616: Viz API calls not working in examples
Example:
http://cartodb.github.io/cartodb.js/examples/leaflet.html

Changing the Viz API call to `https` fixes this issue.

### PR DESCRIPTION
**Pull request by ryanjhodge**
Fixes #616

Working example here based off of `examples/leaflet.html`
http://ryanjhodge.github.io/vegasjs-web-mapping/cartodb-example.html

### CODE REVIEW

**Comment by vhamer** [comment]
Hi @ryanjhodge ! Sorry to be so delayed in my response here. Thanks for submitting this contribution. 

Since this is your first contribution to a CartoDB-managed project, we'll need to obtain a signed Contributor License Agreement (CLA) from you. This is just a document saying affirmatively that we have your approval to incorporate and use the contribution (you of course still own your contribution..it is simply a license to use and distribute). Here's some info on how it works: http://cartodb.com/contributing

Here's the document:
https://drive.google.com/folderview?id=0B_gM2xM2V0_DX3ByYm4ycmlWNTA&usp=sharing

Electronic signature is a-ok. If you made this contribution during the course of work for an employer or client, we'll probably need them to 'sign as an Entity.' Would you review and let me know if you have questions? Then when you (or the Entity) has signed, return it to me via email (cla-support@cartodb.com). 

Thanks again.

Vanessa

**Comment by vhamer** [comment]
Thanks for the signed CLA, Ryan. Reassigning this PR to @xavijam so he can take it from here.

**Comment by nobuti** [comment]
There has been no activity on this issue for several months and that's why we are closing it (automatically). If you think this still needs to be addressed please reopen it. The good news is that we are now working on the next version of CARTO.js, stay tuned.

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
