### PR TITLE
Rounded end for last bin

### PR DESCRIPTION
**Pull request by acanimal**
CR @javisantana 

workaround for #926 
close https://github.com/CartoDB/deep-insights.js/issues/165

This is a workaround to fix a problem with last bucket selection.

### CODE REVIEW

**Comment by javisantana** [comment]
shouldn't that be done server side?
Anyways, I don't follow the logic, in some cases `lastBucket.end` could be really different than max, for example when `lastBucket.end` is 0.0001 and `lastBucket.max` is 0.000999999999 `lastBucket.end` will be 1

**Comment by acanimal** [comment]
Yes the "good" solution would be to solve at server side.

From the sample I saw, the issue is done when the end is lesser than the max value, just the opposite you pointed. In the abel sample we have the bucket computed `lastBucket.end = 0.000999999999` (which is computed at client side width*numbin) and `lastBucket.max is 0.001`. In that case case I change we made end to be the same as max.

For other cases I round the end using ceil.

**Comment by javisantana** [comment]
My question is, why ceil? shouldn't be something according the `bin_width`? In other words, shoudn't it round to the closest bin_width multiplo?

**Comment by javisantana** [comment]
could you add some tests to check the corner cases?

**Comment by acanimal** [comment]
I put to ensure end is "a bit bigger" and fix the round error but I'm thinking it has no sense. The issue always is done when end less than max, like:

- max: 0.01
- end: 0.009999999

**Comment by javisantana** [comment]
:es:

**Pull request merged**
