### PR TITLE
Fixed JS error for image infowindows/popup

### PR DESCRIPTION
**Pull request by xavijam**
Related ticket: https://github.com/CartoDB/cartodb.js/issues/1703.

There is a problem with the broserify-shim in Builder, so better to get rid of the problem and just taking a dependency from npm (y santas pascuas). Also, I've been reviewing the process of loading, so it should work propery now, but it is worth to check it. Things touched:

- [x] Infowindow-view spec linting problems.
- [x] Fix problem using a clip-path plugin/lib.
- [x] Fixing problems with loading image process.
- [x] Add new tests for new changes.
- [x] Review behavior in Builder (not only in CARTO.js).

And now a GIF 💃 

image-infowindow

cc @rubenmoya @piensaenpixel

### CODE REVIEW

**Comment by rubenmoya** [comment]
This is how it looks now:

screen shot 2017-07-26 at 09 28 57

But in acceptance we found a problem related to the size of the image, if the image height is less than the content height the image hook still appearing:

screen shot 2017-07-26 at 09 31 55

The way we fixed it is removing the image hook in that case:

screen shot 2017-07-26 at 09 29 11

cc @CartoDB/design

**Comment by arianaescobar** [comment]
Rubén, you broke my brain using that image as a test. I was SO confused! haha

**Comment by rubenmoya** [comment]
Sorry! It was the first one I found when I was testing it xD

**Comment by arianaescobar** [comment]
The fix looks good :) 

Although I don't fully get what's the problem with adapting the pop-up to the image size as in the first image.

**Comment by rubenmoya** [comment]
The user is the one who chooses the pop-up width, so if the user selects a small width and because of the aspect ratio of the image, the height doesn't cover the content, we end up with that white space.

**Comment by arianaescobar** [comment]
Ooooh right, got it. Then +1 from me.

**Comment by piensaenpixel** [comment]
cool @rubenmoya :)

**Pull request merged**
