### PR TITLE
Set map buttons outline to none

### PR DESCRIPTION
**Pull request by edulix**
The dots that appear in the zoom-in/zoom-out kind of buttons can be annoying, so I propose to remove them. Obvious fix.

### CODE REVIEW

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by Cartofante** [comment]
Can one of the admins verify this patch?

**Comment by xavijam** [comment]
Hey @edulix, thanks for the feedback, for this PR I feel there is no reason for signing the CLA (https://cartodb.com/contributing#obvious-fix). Could you check this @acanimal?

**Comment by acanimal** [comment]
hi @edulix 
which issue are your trying to solve? Could you attach an image with the difference or improvements of your changes?

**Comment by acanimal** [comment]
Close due lack of user feedback.

**Pull request closed without merging**
