### PR TITLE
Ensure bucket has values

### PR DESCRIPTION
**Pull request by acanimal**
CR @xavijam 

Fix issue when buckets has no data.

### CODE REVIEW

**Comment by xavijam** [comment]
I don't have much context, I encourage you to choose another person with better perspective. I checked @javisantana was on charge of the previous PR.
But in any case, I miss a test checking this problem.

**Comment by acanimal** [comment]
I simply modified to ensure lastBucket has a values. Was mea-culpa. Test always helps but IMO for this case I think it is not much useful. Test are useful to check some logic and here the test will simply *check when there is no bin data `parser` do not crashes`, which is something that should do.

**Comment by xavijam** [comment]
IMHO, if something is broken, we didn't notice and none of our tests warned us, we should try to prevent ourselves to fail again.

**Comment by acanimal** [comment]
Added test "for if the flies" :smile: 
When creating test after coding is hard to make all the tests fine, mainly the negative test.

**Comment by xavijam** [comment]
"For if the flies" is valid to me :dancer: :D :+1:

**Comment by xavijam** [comment]
restarted tests in travis

**Comment by xavijam** [comment]
\o/

**Pull request merged**
