### PR TITLE
adds a way to build the current dist without user input

### PR DESCRIPTION
**Pull request by javisantana**
so now we have:

- dist task to build the current version
- default task is dist
- the release task is the one that ask about new version

there were several problems:
- imagemin was failing silently when prompt task was being run so when it's not run everything failed because a bug in imagemin. Does make sense to use imagemin?
- the build was working by chance, some of the needed variables were being added to the config when they should be part of the config from the start
- grunt was not reporting any error and it took 3 hours to realize then the process freeze

### CODE REVIEW

**Comment by javisantana** [comment]
cc @xavijam

**Comment by xavijam** [comment]
retest this please

**Comment by xavijam** [comment]
cc @CartoDB/frontend

**Comment by javisantana** [comment]
cc @azamorano you can execute just grunt to build the current version

**Comment by javisantana** [comment]
cc @CartoDB/frontend please read since the default task has changed

**Comment by xavijam** [comment]
Further to ```imagemin```, we should keep it because it is nice to have a task that optimizes production images. Of course, if we have it, we should make it work properly :D.

**Comment by xavijam** [comment]
In any case :es:.

**Comment by azamorano** [comment]
thanks a lot!! :+1:

**Pull request merged**
