### PR TITLE
Fixes tiler request when the vizjson contains a named map and a torque layer with a named map

### PR DESCRIPTION
**Pull request by javierarce**
We [check](https://github.com/CartoDB/cartodb.js/pull/356/files#diff-e14eff99e7c7b57af717eedd1f3cc9d2R153) if the vizjson contains a named map and torque layer with a named map inside. If that's the case, we don't send the torque layer in the request.

### CODE REVIEW

**Comment by javierarce** [comment]
retest this please

**Comment by javierarce** [comment]
@CartoDB/frontend / @javisantana: can you please have a look at this PR, please?

**Comment by javisantana** [comment]
I'd add a test, this is an edge case that cen be missed in the future pretty easily

**Comment by javierarce** [comment]
@javisantana: spec added. The code was fine for you?

**Comment by javisantana** [comment]
yes yes :es:

**Comment by javierarce** [comment]
Thanks!

**Pull request merged**
