### PR TITLE
Updates version of infowindow template

### PR DESCRIPTION
**Pull request by ohasselblad**
nice and easy :) @javierarce how does it look?

Ref. #481

### CODE REVIEW

**Comment by javierarce** [comment]
:+1: 

Is this associated with a change in the stylesheet?

**Comment by ohasselblad** [comment]
As far as I know it's not associated with a change to the stylesheet. But I could easily be wrong.

**Comment by ohasselblad** [comment]
@javisantana is there anything else I should change in this PR?

**Comment by javisantana** [comment]
I don't know, @javierarce is the reviewer, is everything is fine just merge

**Pull request merged**
