### PR TITLE
Make sure indexes are correct in the styles key

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes CartoDB/cartodb#7422.

@fdansv can you please review this? Thanks!

cc: @javitonino

### CODE REVIEW

**Comment by fdansv** [comment]
Looking good! I was only wondering if in the test, 'Tiled' covers also plain layers. I'm saying this because we often forget to consider plain layers when implementing new stuff and it'd be useful that the test fails whenever that happens.

**Comment by javitonino** [comment]
Hey @alonsogarciapablo. I was going to take a look at this but it is closed, should I take a look anyway?

**Comment by alonsogarciapablo** [comment]
Not sure what happened. I reopened it again.

**Comment by javitonino** [comment]
Works great! Ship it!

**Comment by alonsogarciapablo** [comment]
@fdansv it's not very relevant in this case. I just wanted to test the case where a layer with no cartocss was above the rest of CartoDB layers.

**Comment by alonsogarciapablo** [comment]
Thanks guys!

**Pull request merged**
