### PR TITLE
Don't remove the spaces in the user-submitted addresses using the NOKIA geocoder

### PR DESCRIPTION
**Pull request by javierarce**
See the related issue: https://github.com/CartoDB/cartodb.js/issues/390

I've also enabled the commented specs and added a new one.

### CODE REVIEW

**Comment by javierarce** [comment]
@javisantana or @alonsogarciapablo: do you mind taking a look, please?

**Comment by alonsogarciapablo** [comment]
:+1: 

Perhaps it's a good idea to group specs by the type of geocoder:

```
describe('Geocoder', function() {

   describe('Nokia', function() {
      ...
   });

   describe('Yahoo', function() {
      ...
   });
});
```

**Comment by javierarce** [comment]
Good idea. I've grouped the specs.

**Comment by alonsogarciapablo** [comment]
:+1:

**Pull request merged**
