### PR TITLE
Add browserify transform for templates

### PR DESCRIPTION
**Pull request by viddo**
Let’s :fire: those pesky string concats inside the views

@xavijam @alonsogarciapablo @javierarce

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
:surfer:

**Comment by xavijam** [comment]
You are :top:.

**Comment by javierarce** [comment]
:dancers:

**Comment by viddo** [comment]
tests broken from before in `widgets`… but I'll interpret the comments above as a "code :ok:" ;)

**Pull request merged**
