### PR TITLE
Disabling keyboard map navigation in order to fix iOS focus problem

### PR DESCRIPTION
**Pull request by xavijam**
Keyboard handling is provoking https://github.com/CartoDB/cartodb.js/issues/1652 issue. A reasonable fix is disabling that keyboard behavior until [problem is fixed in Leaflet library](https://github.com/Leaflet/Leaflet/issues/5392).

Sounds ok? @CartoDB/frontend @kevin-reilly 

Also, good thing is we could add the keyboard map option in Builder in the near future, because all logic is ready.

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
👍  looks good codewise.

I'm not sure about the implications of disabling the keyboard for everyone though. Perhaps worth providing the Builder option before releasing this change so that maps keep working the way they were working before and users affected by this option can disable keyboard...

**Comment by xavijam** [comment]
@kevin-reilly and @noguerol, I feel this is your call. Adding the option will take us a bit more of time.

**Comment by nobuti** [comment]
how about to "detect" touch devices and disable keyboard only for those?

**Comment by xavijam** [comment]
> how about to "detect" touch devices and disable keyboard only for those?

It could do the trick too, @alonsogarciapablo yay?

**Comment by xavijam** [comment]
Something like:

```js
keyboard: 'ontouchstart' in window || navigator.msMaxTouchPoints, // #cartodb.js/1652
```

**Comment by alonsogarciapablo** [comment]
Sounds like a good idea @nobuti. I would add a new method in `src/core/util.js`...

**Comment by xavijam** [comment]
Ok! thanks guys, doing it!

**Comment by xavijam** [comment]
Now? @nobuti @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
ok

**Comment by kevin-reilly** [comment]
Thanks guys.  Do you need me to test this at all?

--
*Kevin Reilly*
SVP Product
*CARTO <https://carto.com/> | kevin@carto.com <kevin@carto.com>*
(917) 375-2168

**Comment by xavijam** [comment]
I'll let you know @kevin-reilly, but don't worry 🤗 .

**Pull request merged**
