### PR TITLE
Fixes an invalid route to helper file in SpecRunner.html

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
@xavijam PTAL.

### CODE REVIEW

**Comment by xavijam** [comment]
Ha! good catch, :+1:

**Comment by javisantana** [comment]
I think this file is generated :(

**Comment by alonsogarciapablo** [comment]
I will fix it.

**Comment by alonsogarciapablo** [comment]
Fixed [here](https://github.com/CartoDB/cartodb.js/commit/a671100ef54c9423b49b3d1177897c5103b64592)

**Pull request merged**
