### PR TITLE
fixes bootstrap compatibilites, closes #87, #107

### LINKED ISSUE #87: fix infowindow when working with bootstrap
see this thread https://groups.google.com/forum/#!topic/cartodb/TpbD9ETJPKk

### PR DESCRIPTION
**Pull request by javisantana**
cc @javierarce

### CODE REVIEW

**Comment by javierarce** [comment]
[Caniuse](http://caniuse.com/#feat=css3-boxsizing) reports that there are some issues with Android browsers (see "Known issues"), so I wouldn't recommend have a look. Other than that, :+1:

**Comment by javisantana** [comment]
ok

**Comment by javisantana** [comment]
@javierarce test on android and it works ok

**Comment by javierarce** [comment]
:crossed_flags:

**Pull request merged**
