### PR TITLE
Forcing dataview model fetch new data although sync_on_data_change attribute is disabled

### LINKED ISSUE #1144: If widget has sync_on_data_change disabled, any widget form change doesn't refresh the widget
@xavijam commented on [Wed Feb 24 2016](https://github.com/CartoDB/cartodb/issues/6665)

### STP
- Create a widget (no matter the type).
- Go to style tab within the widget edit/options view.
- Select No for `Unfiltered` attribute.
- Go to data tab and change any other attribute.
- Widget doesn't change when new data arrives.

cc @viddo :joy:

### PR DESCRIPTION
**Pull request by xavijam**
Basically, if a widget has disabled sync_on_data_change, it will not change if there is an update of its 'column'.
We need to test this but I'd like your opinion before doing that. How does this approach sound?

- [ ] Create necessary test(s) for this behaviour.

CR: @alonsogarciapablo

Fixes #1144

### CODE REVIEW

**Comment by viddo** [comment]
I think it would be better (simpler) to have a `.forceFetch()` method of some sort, since the requirements for _editing_ dataview (through a widget) is not the same as for a _using_ them. Having a bunch of implicit behaviors based on various flags states makes it really hard to reason about what's going on.

**Comment by alonsogarciapablo** [comment]
We'd need to something like:

```
// Somewhere in the histogram dataview...
this.on('change:column', this._reloadMapAndForceFetch, this);
```

In the dataview-model-base.js:

```
  _reloadMapAndForceFetch: function () {
    this._map.reload({
      sourceLayerId: this.layer.get('id'),
      forceFetch: true
    });
  }
```

We would need to propagate that "forceFetch" (as we do with the `sourceLayerId`) so that we can finally do something like:

```
// dataview-model-base -> onChangeBinds
    this.on('change:url', function (model, attribute, options) {
      if (options.forceFetch || this._shouldFetchOnURLChange()) {
        this.fetch();
      }
    }, this);
```

**Comment by xavijam** [comment]
@alonsogarciapablo ^^^ that approach?

**Comment by alonsogarciapablo** [comment]
Yes, that can work.

**Comment by xavijam** [comment]
Could you take a look now @alonsogarciapablo?

**Comment by alonsogarciapablo** [comment]
LGTM! :clap:

**Pull request merged**
