### PR TITLE
added full ranges on histogram

### PR DESCRIPTION
**Pull request by ohasselblad**
Ref #567 

Still needs testing, @javierarce.

### CODE REVIEW

**Comment by javierarce** [comment]
Great. @fdansv is going to lead the testing part of the pecan queries (see https://github.com/CartoDB/cartodb.js/issues/612). Let's wait until he's finished on spec for them and use that as an example to test this issue.

**Comment by ohasselblad** [comment]
:+1:

**Comment by ohasselblad** [comment]
Is there anything I can do here to move on this one?

**Comment by fdansv** [comment]
@ohasselblad the tests were added couple weeks ago so there shouldn't be anything blocking this at the moment.

**Comment by javisantana** [comment]
cc @fdansv

**Comment by nobuti** [comment]
There has been no activity on this issue for several months and that's why we are closing it (automatically). If you think this still needs to be addressed please reopen it. The good news is that we are now working on the next version of CARTO.js, stay tuned.

**Pull request closed without merging**
