### PR TITLE
Remove add overlay logo forced

### PR DESCRIPTION
**Pull request by nobuti**
This PR changes the way we handle the logo in cartodb.js. From the builder we are going to update (not create/remove) the logo overlay.

cc @xavijam @alonsogarciapablo

### CODE REVIEW

**Comment by nobuti** [comment]
Not merge yet please.

**Comment by nobuti** [comment]
Ready to review.

**Comment by nobuti** [comment]
Test failing is _unrelated_ with the work of this PR, any ideas?

**Comment by xavijam** [comment]
Weird thing is our CI tests passed

**Comment by alonsogarciapablo** [comment]
:+1: (although I'd personally write a test to ensure that options.logo === false forces the logo to be removed)

**Comment by alonsogarciapablo** [comment]
We probably need to bump the version of camshaft in package.json right?

**Comment by nobuti** [comment]
Test added.

**Pull request merged**
