### PR TITLE
Expose legend model in layer views

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
This is part of #101. It exposes a legend model on layers/sublayers so that users can do some custom things, such us:
- Changing the template of the legend.
- Customizing the title of the legend.
- Showing/hiding the title of the legend.
- Getting/Setting the items that are displayed in the legend.
- Showing/hiding the legend.

@javisantana what do you think?

### CODE REVIEW

**Comment by javisantana** [comment]
:es:

**Comment by knownasilya** [comment]
Sweet :+1:

**Comment by knownasilya** [comment]
How would this be used to create the default legend? `new cdb.geo.ui.Legend({ model: layer.get('legend') })`?

**Comment by alonsogarciapablo** [comment]
@knownasilya You can basically manipulate the legend models (`layer.legend`) to customize your legends. Once this is relased, you will be able to get/set the items, customize the template, show/hide a legend, etc.

**Comment by knownasilya** [comment]
Would love an example of this being used

**Comment by knownasilya** [comment]
Do I have to use `createVis`, or can this be accessed from `createLayer` as well?

**Pull request merged**
