### PR TITLE
Add checker to fullscreen button when it is rendered in an iframe

### PR DESCRIPTION
**Pull request by xavijam**
The problem is iframe content can't be "fullscreen-ed" if the origin/parent url doesn't have a https protocol. And this possible solution would be:

- Check if the map is iframed.
- If so, checks if the parent of the iframe has http protocol.
- If it doesn't have https protocol, fullscreen button is not rendered.

Related:

- Bug in CartoDB: https://github.com/CartoDB/cartodb/issues/4543 
- Happening here: http://mashable.com/2015/07/17/schumer-thrones-google-emmys/#vVL1wykkAZk9
- Explanation: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins 

Using some keys from [here](http://stackoverflow.com/questions/935127/how-to-access-parent-iframe-from-javascript).

Sorry but I'd like to warn all @CartoDB/frontend team.

### CODE REVIEW

**Comment by xavijam** [comment]
I've added a notification just to know what is happening, do you think it is worth it?

**Comment by javierarce** [comment]
Yeah, I think the log is nice.

**Comment by alonsogarciapablo** [comment]
Could we hide the fullscreen button in this situation?

**Comment by xavijam** [comment]
Yes, it will not render the button.

**Comment by alonsogarciapablo** [comment]
:+1:

**Comment by matallo** [comment]
my only concern is with the naming, if I understand correctly it would better be `_canFullScreenBeEnabled`

this is a silly detail, apart from that :+1:

**Comment by xavijam** [comment]
Agree matallo :)

**Comment by xavijam** [comment]
You can test the difference:

Over https: https://dl.dropboxusercontent.com/u/931536/fullscreen/example.html
Over http: http://com.cartodb.users-assets.staging.s3.amazonaws.com/development/example.html

**Pull request merged**
