### PR TITLE
Encodes filters param when instantiating a dashboard

### LINKED ISSUE #778: Filters JSON must be URI encoded
For instance a filter containing a category with `&` char will split the JSON as two query string params.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #778.

@rochoa will this work? Thanks!

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
@xavijam can you take a look at this please?

**Comment by rochoa** [comment]
We are already doing `encodeURIComponent` in some filters: https://github.com/CartoDB/cartodb.js/blob/86d02695231f4b2cb0a6d1d8754914bff688e195/src/windshaft/filters/category.js#L108-L109

I aim for a general solution but we have to check we're not double encoding it.

**Comment by xavijam** [comment]
Agree, we should create a general rule for this. Maybe included in the filter toJSON thing.

**Comment by viddo** [comment]
Why not leave the encoding to when the query string is actually needed instead of having to do this manually? e.g. using https://github.com/sindresorhus/query-string or similar

**Pull request merged**
