### PR TITLE
Remove tangram support

### PR DESCRIPTION
**Pull request by dv343**
https://github.com/CartoDB/cartodb.js/issues/2026

### CODE REVIEW

**Comment by IagoLast** [comment]
@Jesus89 for some reason the bundle size is the same, any ideas?

**Comment by Jesus89** [comment]
The bundle size must be the same because it does not contain the tangram lib

**Comment by IagoLast** [comment]
but we included [tangram.cartodb](https://github.com/CartoDB/cartodb.js/pull/2028/files#diff-33d355f56e59638d50713e9262b8c82aL4) which was around 50K

**Comment by Jesus89** [comment]
But this file is not included in the public bundle

**Comment by dv343** [comment]
Tested on staging, seems good to me, can you CR it @Jesus89 @IagoLast ?

**Comment by Jesus89** [comment]
It seems to work without issues :sparkles:

**Comment by alonsogarciapablo** [comment]
:fire::fire::fire:

**Pull request merged**
