### PR TITLE
[Google Maps] Map provider switch Leaflet <-> Google Maps

### LINKED ISSUE #1527: [Google Map Support] Implement mechanism to switch provider when base layer is changed
# Background

CartoDB.js doesn't currently provide a specific mechanism to switch the base layer (which might have an associated layer for labels on top) of a map. This is currently done "manually" in the context of the BUILDER (i.e: [base and labels layers are added/removed/replaced](https://github.com/CartoDB/cartodb/blob/5a9e83f5fa367985dbc60356c96b0ceb9ac59612/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L252-L297) when a new basemap is selected.)

### Existing types of base layers:

We currently have the following types of layers in our DB:

```
# SELECT DISTINCT(kind) FROM layers group by kind;
    kind
------------
 tiled
 gmapsbase
 torque
 carto
 background
 wms
(6 rows)
```

From those, `tiled`, `gmapsbase`, `background`, and `wms` can be used as base layers. And, there's a different implementation for each type of layer and provider ([Leaflet](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/geo/leaflet/leaflet-layer-view-factory.js#L24-L31) and [Google Maps](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/geo/gmaps/gmaps-layer-view-factory.js#L17-L25)):

### Current implementation in CartoDB.js:

- Leaflet:
  - leaflet-gmaps-tiled-layer-view.js (fallback gmaps -> leaflet (stamen, nokia) (*)
  - leaflet-plain-layer-view.js
  - leaflet-tiled-layer-view.js (also used as labels layer)
  - leaflet-wms-layer-view.js

(*) Not being used at the moment AFAIK.

- Google Maps:

  - gmaps-base-layer-view.js (roadmap, gray_roadmap, dark_roadmap, hybrid, satellite, terrain)
  - gmaps-plain-layer-view.js
  - gmaps-tiled-layer-view.js

**CAUTION:** WMS layers doesn't seem to be currently supported when using Google Maps ([this](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/geo/gmaps/gmaps-layer-view-factory.js#L19) doesn't seem right).

### Current basemap providers:

The BUILDER currently supports the following basemap providers: 

- CARTO (*) -> Tiled layer
- Stamen (*) -> Tiled layer
- Here (NOKIA) -> Tiled layer
- Custom:
  - XYZ -> Tiled layer
  - MAPBOX -> Tiled layer
  - WMS/WMTS -> WMS layer
  - TILEJSON -> Tiled layer
  - NASA -> Tiled layer
- Color -> Plain/Background layer

(*) Some basemaps support labels on top.

Basemaps are defined [here](https://github.com/CartoDB/cartodb-platform/blob/develop/cookbooks/cartodb_app/attributes/basemaps.rb) (internal only).

#### Leaflet

A Leaflet map with a tiled base layer and some labels on top:

```
{
  ...,
  'map_provider': 'leaflet',
  ...
  'layers': [
    {
      ...
      'type': 'tiled',
      'options': {
        urlTemplate: '....',
        ...
      }
      ...
    },
    {
      ...
      'type': 'CartoDB',
      'options': { ... }
      ...
    },
    {
      ...
      'type': 'tiled',
      'options': {
        urlTemplate: '....',
        ...
      }
      ...
    },
  ],
  ...
}
```
### Some interesting guides from the Google Maps JavaScript API docs:

- [Map Types](https://developers.google.com/maps/documentation/javascript/maptypes)
- [Custom Overlays](https://developers.google.com/maps/documentation/javascript/customoverlays)

#### Google Map

A Google Maps map with a "roadmap" base layer and a torque layer on top:

```
{
  ...,
  'map_provider': 'googlemaps',
  ...
  'layers': [
    {
      ...
      'type': 'gmapsbase',
      'options': {
        base_type: 'roadmap',
        style: [ { ... }, ... ]
      }
      ...
    },
    {
      ...
      'type': 'CartoDB',
      'options': { ... }
      ...
    },
    {
      ...
      'type': 'torque',
      'options': { ... }
      ...
    }
  ],
  ...
}

```

The `map_provider` that is received in the viz.json [is set as an attribute of the Map object](https://github.com/CartoDB/cartodb.js/blob/be1da170e3e8a91f2b5565ef00a6ef4887612165/src/vis/vis.js#L157).

# Example, using the actual API:

This is how someone would switch to a Google Maps basemap, using what we have today (not working  #yet):

```
cartodb.createVis('map', function (vis, layers) {
  var baseLayer = vis.getLayer(0);
  var map = vis.map;

  // Remove the current baseLayer
  map.layers.remove(baseLayer);

  // Create a GMapsBase layer at position 0, silently
  map.createGMapsBaseLayer({
    base_type: 'roadmap',
    style: ''
  }, { at: 0, silent: true });

  // Change the map provider
  map.set({ provider: 'googlemaps' });
});
```

# Tasks

- [x] Review test suite and make sure map views and layer views are well tested.
- [x] Re-render visView when map provider changes.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #1527 and #1548

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
Retest this please

**Comment by alonsogarciapablo** [comment]
Retest this please

**Comment by dgaubert** [comment]
I've code reviewed from https://github.com/CartoDB/cartodb.js/pull/1561/commits/454ae65515f9063e5480ebf92dd04426d5aaf13e to https://github.com/CartoDB/cartodb.js/pull/1561/commits/f388756625798005cd11cc58a3cb922c7493692e cause I figure that following commits are intended to update the working branch, right?. Please, let me know if I'm wrong. 

From my understanding everything looks legit. By the way, CI is failing, should we take care of it?

**Comment by alonsogarciapablo** [comment]
@dgaubert Thanks for the CR. I merged `google-maps` branch into to `switch-to-gmaps` to remove all the noise from the list of commits. There are some more commits after `https://github.com/CartoDB/cartodb.js/pull/1561/commits/f388756625798005cd11cc58a3cb922c7493692e`. If you could take a quick look, it would be 👍

**Comment by dgaubert** [comment]
🇨🇭

**Pull request merged**
