### PR TITLE
Di 164 hide layers

### PR DESCRIPTION
**Pull request by acanimal**
CR @alonsogarciapablo 

close https://github.com/CartoDB/deep-insights.js/issues/169 (from DI).

Please Pable review this PR. It solves a problem when there are two layers with widgets and you hide one of them. The widgets are hidden and the second layer widgets works until you make some filter.

Check if my reasoning is correct.
I realize we have generating an array of filters for winshaft map with the filters in the same position as the layer index and holes of no layer of filter is empty.

Supposing we have two layer and we hide one, new info is send to server with only one layer (not two). Later if you filter on a widget of the second layer an array with two positions is sent, the first empty (hole) for filters of the first layer and the second for filter in the layer two), generating an error on server `{"errors":["Cannot read property 'amount-spent-histogram-layer2' of undefined"]}`.

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
Existing code would regenerate would group filters by layer in the resulting JSON object. It will return something like:

```
{
  "layers": [
    // filters for layer 0
    {
      "layer_0_histogram_widget_1": {
        "min": 0,
        "max": 1000
      },
      "layer_0_histogram_widget_2": {
        "min": 10,
        "max": 9000
      }
    },
    // filters for layer 1
    {
      "layer_1_histogram_widget_1": {
        "min": 999,
        "max": 10009
      }
    }
  ]
}
```
If I'm understanding the new code correctly, it will generate something like:

```
{
  "layers": [
    // all filters
    {
      "layer_0_histogram_widget_1": {
        "min": 0,
        "max": 1000
      },
      "layer_0_histogram_widget_2": {
        "min": 10,
        "max": 9000
      }
      "layer_1_histogram_widget_1": {
        "min": 999,
        "max": 10009
      }
    }
  ]
}
```
I haven't tested it out, but I'm not sure Windshaft is prepared to work with all filters grouped in one "layer"... Is it actually working?

**Comment by acanimal** [comment]
Understood, then seems the problem is we are sending filters for layers that are hidden, that is info not sent to server, and windshaft fails, becaus have info about one layer and we are sending filter for two layers.

**Comment by acanimal** [comment]
@alonsogarciapablo Review again Pablo. The issue was `this.client.instantiateMap()` receives a `mapConfig` which only the visible layers but a property `filters` array with a position for each layer (in the case of a hidden layer that position was empty but exists, which make the server return an error).

**Comment by alonsogarciapablo** [comment]
I think we should fix this issue by implementing the changes described in #1020.

We can merge this PR for the time being and start working on #1020.

**Pull request merged**
