### PR TITLE
Animate categories with new animation class

### PR DESCRIPTION
**Pull request by javierarce**
Animate categories with new animation class.

### CODE REVIEW

**Comment by javierarce** [comment]
retest this please

**Comment by javierarce** [comment]
@xavijam: can you review this, please? 

I'm not sure about the location of the `animate_value.js` file. It needs to be a separate class (because of its size and the places where it needs to be used) but it's not so important be core.

**Comment by xavijam** [comment]
I'd leave it where it is, within widgets folder.

**Comment by javierarce** [comment]
Ok, thanks! It's ok if I merge this, right?

**Comment by xavijam** [comment]
:+1:

**Pull request merged**
