### PR TITLE
Search popup

### PR DESCRIPTION
**Pull request by xavijam**
New search popup :).

screen shot 2015-12-18 at 09 39 24
screen shot 2015-12-18 at 09 39 31

REVIEWER: @viddo

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
@xavijam I see you have fixed a bunch of issues to make the JS linter happy (eg: `src/geo/ui/infowindow.js`) :). Should we remove those files from `.eslintignore` so that they are not ignored?

**Comment by xavijam** [comment]
Arg, true, let me remove them from there, thanks @alonsogarciapablo.

**Comment by xavijam** [comment]
Ping @viddo :P

**Comment by viddo** [comment]
:+1:

**Pull request merged**
