### PR TITLE
Remove header overlay

### PR DESCRIPTION
**Pull request by xavijam**
Fixes https://github.com/CartoDB/cartodb-management/issues/4708#issuecomment-262475222.
CR: @alonsogarciapablo

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
:fire::fire::fire: should we also remove this from the viz.json/DB?

**Comment by xavijam** [comment]
What's that @alonsogarciapablo ?

**Comment by xavijam** [comment]
Ahh, the DB extension from new CARTO you mean?

**Comment by xavijam** [comment]
that in another PR I feel, 😛

**Comment by alonsogarciapablo** [comment]
Yes, this PR is perfect. I was just wondering if we should make sure this type of overlays is not included in the viz.json anymore...

**Comment by xavijam** [comment]
We could do that, but it will need a viz.json cache flush in order to "clean" that. I'm not sure if it is worth it.

**Comment by xavijam** [comment]
Merging!

**Pull request merged**
