### PR TITLE
[DON'T MERGE YET] Update perfect scrollbar dependency.

### PR DESCRIPTION
**Pull request by nobuti**
This PR updates the perfect scrollbar library to fix https://github.com/CartoDB/cartodb/issues/11190. You can read more about what it's included in the update here: https://github.com/nobuti/perfect-scrollbar/pull/1

### CODE REVIEW

**Comment by xavijam** [comment]
Adding @alonsogarciapablo to the loop, but merging as soon as possible.

**Comment by xavijam** [comment]
Let's merge this one first, right?

**Comment by nobuti** [comment]
Yes, this first, then DI.

**Comment by xavijam** [comment]
Merging1

**Pull request merged**
