### PR TITLE
fix custom infowindows

### PR DESCRIPTION
**Pull request by piensaenpixel**
@xavijam could you take a look?

image

cc/ @javisantana

### CODE REVIEW

**Comment by javisantana** [comment]
There is problem in the migration, the data is not being rendered, is something related to the migration @juanignaciosl ?

**Comment by juanignaciosl** [comment]
I don't know, I can't reproduce that problem with master: although the style is not kept, the data is replaced (``{{my_column}}`` gets replaced by the data).

**Comment by xavijam** [comment]
Apart from the thing @javisantana has mentioned, I'm ok with the change.

**Comment by piensaenpixel** [comment]
so can we merge this one or waiting for?

**Comment by juanignaciosl** [comment]
I can't reproduce the problem with the data.

**Comment by xavijam** [comment]
merge it

**Pull request merged**
