### PR TITLE
Reload map when type of analyses change

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
@xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
:dancer: :dancers:  thanks!

**Comment by alonsogarciapablo** [comment]
Anyway, if you're changing the `type` of an analysis, I asume you're also changing some of the params of that analysis, so [this already existing binding](https://github.com/CartoDB/cartodb.js/pull/1230/files#diff-c5288cba30a7a70973afdc0e3816deb5R20) should cause the map to be reloaded...

**Comment by xavijam** [comment]
So I realized that, If we change the type of the analysis, this solution doesn't work because new type params are not binded, so we should re-bind new type params when it has changed.

**Comment by alonsogarciapablo** [comment]
:+1: (after adding a new test for the last commit)

**Comment by alonsogarciapablo** [comment]
:+1:

**Comment by alonsogarciapablo** [comment]
retest this please

**Comment by alonsogarciapablo** [comment]
retest this please

**Comment by xavijam** [comment]
retest this please

**Comment by xavijam** [comment]
:clap:

**Pull request merged**
