### PR TITLE
Replaces clip path plugin with a cross-browser version

### PR DESCRIPTION
**Pull request by javierarce**
screen shot 2015-12-18 at 10 24 08

### CODE REVIEW

**Comment by piensaenpixel** [comment]
\o/

**Comment by javierarce** [comment]
Please, have a look, @xavijam

**Comment by xavijam** [comment]
I encourage you @javierarce to check infowindow.js with standard.js and remove this file (and rest of .js you have touched) from ```.eslintignore```. :)
For the rest, :+1: .

**Comment by javierarce** [comment]
Oh, yeah, I'll do that, thanks

**Comment by javierarce** [comment]
It's failing because this error:

```infowindow.js:4:5: "ClipPath" is defined but never used```

Not sure how to fix this :/

**Pull request merged**
