### PR TITLE
Fixing btoa method within cartodb.js utils

### LINKED ISSUE #692: Layers with very long CartoCSS are not working under IE9
### STR

- Create a map in CartoDB with only a layer. 
- Add a very long CartoCSS for that layer.
- Create a new html trying to recreate that map (```...createVis()```).
- Test that map in Chrome, it should work.
- Test that map in IE9 (Win 7?).

### Happening
- The map will not show the CartoDB layer, but no error appears.
- Check the last request sent (GET), it goes to /api/vX/map and it contains javascript code on it.

### Expected
- Due to IE9 doesn't support CORS, it should use [LZMA](https://github.com/nmrugg/LZMA-JS) for compressing the request params. But in any case, that petition should not include JS vars or code on it.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes #692.

### CODE REVIEW

**Comment by xavijam** [comment]
:+1: Vamos neno!
cc @iriberri @oriolbx

**Comment by iriberri** [comment]
@ztephm: this will fix the IE9 issue :)

**Comment by ztephm** [comment]
great thanks guys!

**Comment by alonsogarciapablo** [comment]
We just did a new release and this fix is included in CartoDB.js 3.15.8.

Great job with the fix @xavijam!

**Comment by xavijam** [comment]
No no, was @rochoa :D

**Comment by alonsogarciapablo** [comment]
Great job with the fix @rochoa! :)

**Comment by rochoa** [comment]
:see_no_evil:

**Comment by iriberri** [comment]
:revolving_hearts:

**Comment by oriolbx** [comment]
:+1:

**Pull request merged**
