### PR TITLE
Upgraded mustache.js to v1.1.0

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
@CartoDB/frontend., this PR bumps the version of mustache.js from v0.5.2 to v1.1.0.

We (@javisantana and I) discovered a bug in mustache.js when investigating cartodb/cartodb#2420 and this bump fixes it.

PTAL @javisantana, @xavijam

### CODE REVIEW

**Comment by xavijam** [comment]
New mustache! :dancer:

**Comment by xavijam** [comment]
We should check mustache templates with different mustache libraries, shouldn't we?

**Comment by javisantana** [comment]
basically the things that can break are the infowindows but if you tried every template we have in cartodb we are pretty safe

**Comment by alonsogarciapablo** [comment]
When I run `grunt dist`, the new version of mustache is not being included in the dist files :-(. It turns out, we are not including the file under `vendor/mustache.js`. Instead, we're relaying on the mustache.js that comes with `wax.cartodb.js` (v0.5.5).

**Pull request merged**
