### PR TITLE
refactored sql and added new functions for analysis

### PR DESCRIPTION
**Pull request by ohasselblad**
I did some refactoring and added two new functions that are in postgresql extension (CDB_Kurtosis and CDB_Skewness).

/cc @javierarce @xavijam

### CODE REVIEW

**Comment by javierarce** [comment]
I'm not an SQL expert, but the refactor part looks good :+1:

**Comment by javierarce** [comment]
retest this please

**Comment by ohasselblad** [comment]
I'm having trouble tracing down the cause of that error.. Any ideas?

**Comment by javierarce** [comment]
retest this please

**Comment by javierarce** [comment]
Maybe @fdansv can have a look?

**Comment by xavijam** [comment]
@fdansv ?

**Comment by fdansv** [comment]
Sorry I completely missed this mention at the time it was posted.

@ohasselblad I can't see the error anymore as the CI system is 404'ing...

**Comment by fdansv** [comment]
retest this please

**Comment by ohasselblad** [comment]
latest commit removes one of the causes of test failures (naming difference and removal of variable no longer in use). The other error I'm seeing is giving this back (which doesn't seem related to the code changes here):

```
X Image should use the basemap defined in the vizjson
   Expected Object({ options: Object({ visible: true, type: 'Tiled', urlTemplate: 'https://{s}.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?lg=eng&token=A7tBPacePg9Mj_zghvKt9Q&app_id=KuYppsdXZznpffJsKT24', subdomains: '1234', name: 'Nokia Day', className: 'nokia_day', attribution: '©2012 Nokia <a href='http://here.net/services/terms' target='_blank'>Terms of use</a>' }), infowindow: null, tooltip: null, id: '2c4a8c5e-2ba5-4068-8807-d916a01b48d5', order: 0, type: 'tiled' }) to equal Object({ options: Object({ visible: true, type: 'Tiled', urlTemplate: 'https://{s}.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?lg=eng&token=A7tBPacePg9Mj_zghvKt9Q&app_id=KuYppsdXZznpffJsKT24', subdomains: '1234', name: 'Nokia Day', className: 'nokia_day', attribution: '©2012 Nokia <a href='http://here.net/services/terms' target='_blank'>Terms of use</a>' }), infowindow: null, tooltip: null, id: '2c4a8c5e-2ba5-4068-8807-d916a01b48d5', order: 0, parent_id: null, children: [  ], type: 'tiled' }).
   Error: Expected Object({ options: Object({ visible: true, type: 'Tiled', urlTemplate: 'https://{s}.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?lg=eng&token=A7tBPacePg9Mj_zghvKt9Q&app_id=KuYppsdXZznpffJsKT24', subdomains: '1234', name: 'Nokia Day', className: 'nokia_day', attribution: '©2012 Nokia <a href='http://here.net/services/terms' target='_blank'>Terms of use</a>' }), infowindow: null, tooltip: null, id: '2c4a8c5e-2ba5-4068-8807-d916a01b48d5', order: 0, type: 'tiled' }) to equal Object({ options: Object({ visible: true, type: 'Tiled', urlTemplate: 'https://{s}.maps.nlp.nokia.com/maptile/2.1/maptile/newest/normal.day/{z}/{x}/{y}/256/png8?lg=eng&token=A7tBPacePg9Mj_zghvKt9Q&app_id=KuYppsdXZznpffJsKT24', subdomains: '1234', name: 'Nokia Day', className: 'nokia_day', attribution: '©2012 Nokia <a href='http://here.net/services/terms' target='_blank'>Terms of use</a>' }), infowindow: null, tooltip: null, id: '2c4a8c5e-2ba5-4068-8807-d916a01b48d5', order: 0, parent_id: null, children: [  ], type: 'tiled' }).
```

**Comment by nobuti** [comment]
There has been no activity on this issue for several months and that's why we are closing it (automatically). If you think this still needs to be addressed please reopen it. The good news is that we are now working on the next version of CARTO.js, stay tuned.

**Pull request closed without merging**
