### PR TITLE
Adds info panel to the left hand side of dashboards

### LINKED ISSUE #857: add js for show and hide bar info

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Some important stuff to review:

- I added some new fields to the viz.json with information for the info bar.
- I introduced a new dependency (moment.js) which I'm using to format a date.
- We currently don't have a model for visualization/dahsboards to pass to this new view, so I decided to go for a basic Backbone.Model.

Also, I think this view will need to be part of a DashboardCanvasView or similar in the near future.

@xavijam what do you think?

Close #857

### CODE REVIEW

**Comment by xavijam** [comment]
Come on, add a screenshot! :P

**Comment by xavijam** [comment]
For me looks great! :+1:

**Comment by alonsogarciapablo** [comment]
You got it... sidebar

**Comment by xavijam** [comment]
:dancer:

**Pull request merged**
