### PR TITLE
[WIP] createVis supports authToken option

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
Fixes https://github.com/CartoDB/cartodb.js/issues/1381.

cc: @javitonino... do you think we should leave the actual code (i.e: getting auth tokens from viz.json) as a fallback?

### CODE REVIEW

**Comment by javitonino** [comment]
I think that we can remove it, as we will start passing the token via the embed at the same time.

We also need to support multiple auth tokens (as in cartodb.js 3), although I think passing an array as the authToken might work with this change (I'll check and report back).

**Comment by javitonino** [comment]
So I've just tested this, and this only allows passing a single auth token parameter. Passing an array of auth tokens makes it post an incorrect request to the maps API: `&auth_token=%5B%22Fv7Wi4BsA6tCNaN7r2qGtg%22%2C%22b%22%5D` (JSON encoded array).

Can we make it work like in v3 (https://github.com/CartoDB/cartodb.js/blob/2e26d00a1fd40e385918ce05ae45b236bc61ebb1/src/geo/layer_definition.js#L165)?

**Comment by javitonino** [comment]
Added support for multiple tokens. Also added authToken to the widgets data models, as they were not working with password protected/privately shared maps (also in production).

**Comment by xavijam** [comment]
I see the pattern/method for auth_tokens repeated several times in the dataview models, but in any case :+1:

**Pull request merged**
