### PR TITLE
Removes unused UI components + most of cdb.XXX stuff 🔥 

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
This PR removes (🔥 ) some UI components that live in `src/ui/common` and are not currently used:

- Annotation
- Dialog
- Dropdown
- Infobox
- Image
- Layer View
- Notification
- Table (Row, TableData, TableProperties, RowView)
- TabPane
- Text

We can always "recover" them from CartoDB.js v3.X if we need to.

This PR also removes a lot of stuff from `window.cdb` object (see https://github.com/CartoDB/cartodb.js/pull/1642 for more info).

cc: @donflopez @rochoa 

Fixes https://github.com/CartoDB/cartodb.js/issues/1407.

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
cc: @xavijam

**Comment by xavijam** [comment]
I'd not remove the annotation because we should provide it in Builder like any other overlay. But 👍 .

**Comment by alonsogarciapablo** [comment]
We can always bring back the code to render annotation overlays when we start supporting them in BUILDER.

**Comment by alonsogarciapablo** [comment]
cc: @IagoLast

**Pull request merged**
