### PR TITLE
Newdocs

### PR DESCRIPTION
**Pull request by csobier**
@matallo , trying to view this as part of the ./docs_build.sh in the expose-torque.js branch. Not happening. How do I set up these two WIP branches to communicate?

### CODE REVIEW

**Comment by matallo** [comment]
first, make sure the development branch is updated from `develop` for the "This branch has conflicts that must be resolved" message not appear, solving this conflict myself this time

**Comment by csobier** [comment]
You need to show me step by step how to do this please, this process is not intuitive.

**Comment by matallo** [comment]
this has been explained step by step in the next comment: https://github.com/CartoDB/docs/pull/555#issue-118841070

**Comment by csobier** [comment]
@matallo  , please merge the Torque.js content! This includes:

- This torque branch, [PR #248](https://github.com/CartoDB/torque/pull/248) (split files)
- Docs repo, expose-torquejs branch [PR#552](https://github.com/CartoDB/docs/pull/552)
- CartoDB.js repo, newdocs branch [PR#939](https://github.com/CartoDB/cartodb.js/pull/939)- shows updated time slider value descriptions

Let me know if you have any questions.

**Comment by matallo** [comment]
just made an edit commenting torqueslidertimevalue as it doesn't seem to be included in the torque docs https://github.com/CartoDB/cartodb.js/commit/155dfe490c101e0e5f782658bd3ce5c866d55947

besides that :+1:

**Pull request merged**
