### PR TITLE
CartoDB -> CARTO - cartodb.com -> carto.com

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
- Changes CartoDB by CARTO
- Changes cartodb.com by carto.com
- Changes these things (:point_up:) in default attribution

cc: @matallo @csobier @xavijam @javitonino

### CODE REVIEW

**Comment by javitonino** [comment]
I think `http://docs.carto.com` should be `https://carto.com/docs`. But the redirect works, so it is not very important. LGTM :+1:

**Comment by matallo** [comment]
LGTM, tests failing?

**Comment by alonsogarciapablo** [comment]
Retest this please.

**Comment by xavijam** [comment]
👍

**Pull request merged**
