### PR TITLE
Widgets tooltip

### PR DESCRIPTION
**Pull request by xavijam**
New tooltip! Thanks to @piensaenpixel who has done all the hard work!

screen shot 2015-12-21 at 22 11 19

REVIEWER: @viddo

### CODE REVIEW

**Comment by viddo** [comment]
:+1: but no styleguide examples in this case then?

**Comment by xavijam** [comment]
@piensaenpixel ^^^?

**Comment by piensaenpixel** [comment]
yes @viddo i'll add today

**Comment by piensaenpixel** [comment]
pushed the styleguide :D

**Pull request merged**
