### PR TITLE
bump jQuery version from 1.7.2 to 1.11.3

### PR DESCRIPTION
**Pull request by nerik**
Updated jquery to latest minor in 1.x branch.
Bootstrap requires jQuery at least 1.9.1.
```
Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
```
This means that as of now we are forced to load jQuery again, on top of the version bundled in CartoDB.js / or use the version without jQuery : see for example https://github.com/chriswhong/cartodb-bootstrap-template/blob/master/index.html#L115

Ping @viddo :)

### CODE REVIEW

**Comment by viddo** [comment]
Seems like this bump of the minor version introduces changes that break some tests, you'd have to fix those before this change can be merged. I'm not familiar with the failing tests, perhaps @javierarce can give more info on what might be wrong?

Also, in addition to the automated tests, we should probably verify that the examples work still.

**Comment by javierarce** [comment]
@nerik: one of the problems that I'm seeing running the specs locally is the deprecation of `$.browser.msie` in jQuery 1.9. You can see how we solved this issue in the branch `v4` (have a look to [util.js](https://github.com/CartoDB/cartodb.js/blob/v4/src/core/util.js) too)

**Comment by javierarce** [comment]
Regarding the `Expected undefined to equal null` errors, those were fixed in `v4` by changing the expectation of the test (so instead of `.toEqual(null)` we wrote `.toEqual(undefined)`).

**Comment by viddo** [comment]
@javierarce ok, doesn't sound too serious, so should be safe to release a new minor version once those are fixed, right?

**Comment by nerik** [comment]
Thanks for the replies guys.
Let me fix this once I find the time to set up and run the test suite on my machine.

**Comment by javierarce** [comment]
Great :)

@viddo: yes, I think it should be ok (but, @nerik, please make sure we don't have any other `$.browser.msie` in other places in our code).

**Comment by nerik** [comment]
Should be fixed. Do you want me to squash?

**Comment by nerik** [comment]
Gosh, Jenkins is picking up more errors.

**Comment by javierarce** [comment]
If you verified that the demos in the example folder are working too, you are good to go :)

**Comment by nerik** [comment]
Sorry to answer so late. Do I have to verify ALL of the examples? Some of them seem half broken, but is it because of this PR ? Example, core.html :
screen shot 2016-01-15 at 16 21 00

Also any sensitive browser you think I should check? IE?

**Pull request closed without merging**
