### PR TITLE
Fixes FRA, issue 29

### PR DESCRIPTION
**Pull request by csobier**
@inigomedina 

Fixes https://github.com/CartoDB/full-reference-api/issues/29

### CODE REVIEW

**Comment by Jesus89** [comment]
@csobier we don't want to merge `v4` in `develop` yet.

Also, the issue https://github.com/CartoDB/full-reference-api/issues/29 is still not fixed in `v4`. Do we want to add a `setZIndex` function for the carto layers?

**Comment by csobier** [comment]
@Jesus89, OK, good to know. Thanks.

Yes, if there is time to add new code before the beta, please add. If not, we can create a new issue for the public release.

**Comment by Jesus89** [comment]
We can add little changes for the beta on Monday, but we need to have clear the API for this.

Now the Leaflet layers has its own setZIndex function so we need to distinguish it in the docs from the Carto layer `setZIndex(<number>)`. May be `bringToFront()` and `bringToBack()`functions are useful too.

**Comment by Jesus89** [comment]
From the team, we have decided to freeze the development for the beta release and we will think about Carto layers ordering in next versions.

**Comment by csobier** [comment]
I 100% agree to code freeze, so we need to include how to reorg the layers with what we have. Is the text description from this PR okay?

**Comment by Jesus89** [comment]
-> https://github.com/CartoDB/full-reference-api/issues/29

**Pull request closed without merging**
