### PR TITLE
Adds d3.js

### PR DESCRIPTION
**Pull request by javierarce**

### CODE REVIEW

**Comment by javierarce** [comment]
cc @xavijam @alonsogarciapablo

**Comment by xavijam** [comment]
:+1:

**Comment by javierarce** [comment]
Thanks! 

I talked to @viddo and I'm going to wait until he's done with the browserify refactor to include this library.

**Comment by viddo** [comment]
finally closing this, once `v4-browserify`#699 branch is merged to `v4` whoever needs d3 can just do a `npm install d3` and require('d3') where it's needed

**Comment by viddo** [comment]
finally closing this, once v4-browserify#699 branch is merged to v4 whoever needs d3 can just do a npm install d3 and require('d3') where it's needed

**Pull request closed without merging**
