### PR TITLE
Updates to jQuery v2.1.4

### PR DESCRIPTION
**Pull request by javierarce**
- Updated to jQuery v2.1.4
- Fixed several failing specs
- Updated a call to a deprecated method ($.browser.msie) with our own cdb.core.util.browser
- Updated mwheelIntent.js to fix a bug with jQuery
- Manually tested all the examples in Chrome, Safari, Firefox and IE > 8

### CODE REVIEW

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by jesusvazquez** [comment]
retest this please

**Comment by javierarce** [comment]
@xavijam: all yours

**Comment by javierarce** [comment]
@xavijam: ping

**Comment by javierarce** [comment]
@alonsogarciapablo: can you take care of the review, please?

**Comment by alonsogarciapablo** [comment]
:+1:

**Pull request merged**
