### PR TITLE
Abort previous requests to the Maps API before sending a new one

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
@javisantana Didn't think too much about this, but this could be a start... what do you think? Am I missing something (apart from some tests 😄)? Thanks!

### CODE REVIEW

**Comment by javisantana** [comment]
probably is enough. I don't know if cancelling a request is enough for the maps api to cancel the whole thing cc @rochoa

**Comment by javisantana** [comment]
but from the cartodb.js that's good enough I'd say

**Comment by rochoa** [comment]
This is kind of related to:
 - https://github.com/CartoDB/cartodb/issues/8052.
 - https://github.com/CartoDB/Windshaft/issues/176.

We have to start thinking about the best way to handle _cancellations_.

**Comment by alonsogarciapablo** [comment]
Ok. I'll add some tests and merge this as a first step. It we implement a mechanism to cancel stuff that is in progress, we can build it on top of this. Thx

**Pull request merged**
